### ISSUE TITLE
Evaders lose :(

### ISSUE THREAD

**Issue by leksito** [paulirish/headless-cat-n-mouse#18]
Evaders are winning, but captcha on tmall.com detects headless chrome.
![image](https://user-images.githubusercontent.com/13941862/49737472-08f36000-fc9e-11e8-9f35-bb2516fad04f.png)
![image](https://user-images.githubusercontent.com/13941862/49737490-16104f00-fc9e-11e8-88de-6a185769ff13.png)
Evaders lose :(

**Comment by ThatAnton** [comment]
This login UI loads via an iframe. I'm pretty sure iframes are bypassing all of the navigator overrides this repo is trying to cover and therefore Evaders lose.
