### ISSUE TITLE
Can be detected by WebGL in headless mode

### ISSUE THREAD

**Issue by stereobooster** [paulirish/headless-cat-n-mouse#2]
As of now WebGL not supported in headless mode see https://github.com/mapbox/mapbox-gl-js/issues/5460. To evade add `const browser = await puppeteer.launch({headless: false})`

**Comment by paulirish** [comment]
I did write a test for this....

<details>

```js
  // thx https://github.com/Modernizr/Modernizr/blob/master/feature-detects/webgl.js
  await test('WebGL unavailable', _ => {
    const canvas = document.createElement('canvas');
    const probablySupports = 'probablySupportsContext';
    const supports = probablySupports in canvas ? probablySupports : 'supportsContext';
    if (supports in canvas) {
      return (canvas[supports]('webgl') || canvas[supports]('experimental-webgl')) === false;
    }
    return ('WebGLRenderingContext' in window) === false;
  });
```

</details>

... but as it turns out, headless is now supported in headless: https://bugs.chromium.org/p/chromium/issues/detail?id=617551

so this technique won't work any longer.
