### ISSUE TITLE
Cannot redefine property 'plugins'

### ISSUE THREAD

**Issue by crislin2046** [paulirish/headless-cat-n-mouse#23]
This seems to be changed recently in Chrome.

**Comment by crislin2046** [comment]
If one runs Chrome without headless using XVFB plugins are as normal.

**Comment by antoinevastel** [comment]
I currently have no error, which version of Chrome are you using?

**Comment by crislin2046** [comment]
73, sir.

**Comment by crislin2046** [comment]
73, sir.

**Comment by antoinevastel** [comment]
I am using Chrome version 74 and I have no problems to override the plugins.

**Comment by crislin2046** [comment]
Good to know
