### ISSUE TITLE
Boys the game goes on

### ISSUE THREAD

**Issue by NikolaiT** [paulirish/headless-cat-n-mouse#26]
https://antoinevastel.com/bot%20detection/2019/07/19/detecting-chrome-headless-v3.html

fpCollect is the name of the new variant: https://arh.antoinevastel.com/javascripts/fpCollect.min.js

**Comment by berstend** [comment]
The latest version of the [stealth plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) now passes all tests 😄 But I fully expect this to change in the future again (I forgot if we're the cat or mouse here).

**Comment by NikolaiT** [comment]
> The latest version of the [stealth plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) now passes all tests  But I fully expect this to change in the future again (I forgot if we're the cat or mouse here).

Korrekter typ
